---

name: Make Release

on:
  push:
    tags:
      # change based on pipeline
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create release
        id: create_release
        uses: comnoco/create-release-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            changes
            - First Change
            - Second Change
